routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation', 'Frontend\ReservationController@reserve')->name('reservation');
Route::post('/contact','Frontend\ContactController@contact')->name('contact');



Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'admin'], function(){

	Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');
	Route::resource('slider','SliderController');
	Route::resource('category','CategoryController');
	Route::resource('item','ItemController');
	Route::get('reservation','ReservationController@index')->name('reservation.index');
	Route::post('reservation/{id}','ReservationController@status')->name('reservation.status');
	Route::delete('reservation/{id}','ReservationController@destroy')->name('reservation.destroy');
    Route::get('contact','ContactController@contact')->name('contact.index');
    Route::get('contact/{id}','ContactController@show')->name('contact.show');
    Route::delete('contact/{id}','ContactController@destroy')->name('contact.destroy');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function categoryItems()
    {
    	return $this->hasMany('App\Models\Item');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories= Category::all();
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[

            'name'=>'required'
        ]);

        $category=new Category();
        $category->name = $request->name;
        $category->slug = str_slug($request->name);
        $category->save();
        return redirect()->route('category.index')->with('successMsg','Category successfully added!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category= Category::find($id);
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[

            'name'=>'required'
        ]);

        $category= Category::find($id);
        $category->name = $request->name;
        $category->slug = str_slug($request->name);
        $category->save();
        return redirect()->route('category.index')->with('successMsg','Category successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return redirect()->back()->with('successMsg','Category successfully updated!');
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.app')

@section('title','Category')

@push('css')
	

	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

              @include('layouts.partial.message')

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Add Category</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  
                    <form method="POST" action="{{route('category.store')}}" enctype="multipart/form-data">
                      @csrf
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Category Name</label>
                            <input type="text" class="form-control" name="name">
                          </div>
                        </div>
                        <br>
                        <a href="{{route('category.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Add Category</button>
                        

                        
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	
@endpush

resources/views/admin/category/edit.blade.php
@extends('layouts.app')

@section('title','Category')

@push('css')
	

	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

              @if ($errors->any())
                      
                    @include('layouts.partial.message')

              @endif

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Edit Category</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  
                    <form method="POST" action="{{route('category.update', $category->id)}}">
                      @csrf

                      @method('PUT')

                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Category Name</label>
                            <input type="text" class="form-control" name="name" value="{{$category->name}}">
                          </div>
                        </div>
                        <br>
                        <a href="{{route('category.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Update Category</button>
                        

                        
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	
@endpush

resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('title','Category')

@push('css')
	
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <a href="{{route('category.create')}}" class="btn btn-info">Add New Category</a>

              @include('layouts.partial.message')

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">All Category</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="myTable" class="table table-striped table-bordered " style="width:100%;">
                      <thead class=" text-primary">
                        <th>
                          ID  
                        </th>
                        <th>
                          Category Name
                        </th>
                        <th>
                          Slug
                        </th>
                        <th>
                          Action
                        </th>
                      </thead>
                      <tbody>
              @foreach($categories as $key=>$category)


							<tr>
								<td>{{$key+1}}</td>
								<td>{{$category->name}}</td>
								<td>{{$category->slug}}</td>
								<td class="text-center">

                  <a href="{{route('category.edit', $category->id)}}"><i class="material-icons mr-3 text-warning mb-3">edit</i></a>

                  <form id="delete-form-{{$category->id}}" action="{{route('category.destroy', $category->id)}}" style="display: none;" method="POST">
                    @csrf
                    @method('DELETE')
                  </form>
                  <button type="button" style="border:none;background: none;" onclick="if (confirm('Are you sure? You want to delete this Category!')) {
                        event.preventDefault();
                        document.getElementById('delete-form-{{$category->id}}').submit();
                      }else{
                        event.preventDefault();
                      }"><i style="cursor: pointer; width: 100%;" class="material-icons text-danger">delete</i>
                  </button>
                    
                </td>
							</tr>


                         @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

	<script>
		$(document).ready(function() {
		    $('#myTable').DataTable();
		} );
	</script>
	
@endpush