routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation', 'Frontend\ReservationController@reserve')->name('reservation');
Route::post('/contact','Frontend\ContactController@contact')->name('contact');



Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'admin'], function(){

	Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');
	Route::resource('slider','SliderController');
	Route::resource('category','CategoryController');
	Route::resource('item','ItemController');
	Route::get('reservation','ReservationController@index')->name('reservation.index');
	Route::post('reservation/{id}','ReservationController@status')->name('reservation.status');
	Route::delete('reservation/{id}','ReservationController@destroy')->name('reservation.destroy');
    Route::get('contact','ContactController@contact')->name('contact.index');
    Route::get('contact/{id}','ContactController@show')->name('contact.show');
    Route::delete('contact/{id}','ContactController@destroy')->name('contact.destroy');
});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    public function itemCategory()
    {
    	return $this->belongsTo('App\Models\Category', 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/ItemController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Item;
use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::all();
        //dd($items);
        return view('admin.item.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.item.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'          => 'required',
            'category'      => 'required',
            'description'   => 'required',
            'price'         => 'required',
            'image'         => 'required|mimes:jpeg,jpg,png,bmp'
        ]);
        $image = $request->file('image');
        $slug = str_slug($request->name);
        if (isset($image)) 
        {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if (!file_exists('upload/item')) 
            {
                mkdir('upload/item', '0777', 'true');
            }
            $image->move('upload/item', $imageName);
        }else{
            $imageName = 'default.jpg';
        }
        $item = new Item();
        $item->category_id  = $request->category;
        $item->name         = $request->name;
        $item->description  = $request->description;
        $item->price        = $request->price;
        $item->image        = $imageName;
        $item->save();
        return redirect()->route('item.index')->with('successMsg','Item successfully created!!!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Item::find($id);
        $categories = Category::all();
        return view('admin.item.edit', compact('item', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'          => 'required',
            'category'      => 'required',
            'description'   => 'required',
            'price'         => 'required',
            'image'         => 'mimes:jpeg,jpg,png,bmp'
        ]);
        $item = Item::find($id);
        $image = $request->file('image');
        $slug = str_slug($request->name);
        if (isset($image)) 
        {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
            if (!file_exists('upload/item')) 
            {
                mkdir('upload/item', '0777', 'true');
            }
            unlink('upload/item/'.$item->image);
            $image->move('upload/item', $imageName);
        }else{
            $imageName = $item->image;
        }
        $item->category_id  = $request->category;
        $item->name         = $request->name;
        $item->description  = $request->description;
        $item->price        = $request->price;
        $item->image        = $imageName;
        $item->save();
        return redirect()->route('item.index')->with('successMsg','Item successfully updated!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::find($id);
        if (file_exists('upload/item/'.$item->image)) 
        {
            unlink('upload/item/'.$item->image);
        }
        $item->delete();
        return redirect()->back()->with('successMsg','Item successfully deleted!!!');
    }
}

resources/views/admin/item/create.blade.php
@extends('layouts.app')

@section('title','Item')

@push('css')
	

	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

              @include('layouts.partial.message')

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Add Item</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  
                    <form method="POST" action="{{route('item.store')}}" enctype="multipart/form-data">
                      @csrf
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Item Name</label>
                            <input type="text" class="form-control" name="name">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Select Category</label>
                            <select name="category" class="form-control">
                              @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                              @endforeach
                            </select>
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Description</label>
                            <input type="text" class="form-control" name="description">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Price</label>
                            <input type="number" class="form-control" name="price">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <label class="bmd-label-floating">Image</label>
                          <input type="file" class="form-control" name="image">
                        </div>
                        <br>

                        <a href="{{route('item.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Save this</button>
                        
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	
@endpush

resources/views/admin/item/edit.blade.php
@extends('layouts.app')

@section('title','Item')

@push('css')
	

	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

              @if ($errors->any())
                      
                    @include('layouts.partial.message')

              @endif

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Edit Item</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  
                    <form method="POST" action="{{route('item.update', $item->id)}}" enctype="multipart/form-data">
                      @csrf

                      @method('PUT')

                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Item Name</label>
                            <input type="text" class="form-control" value="{{ $item->name }}" name="name">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Select Category</label>
                            <select name="category" class="form-control">
                              @foreach($categories as $category)
                                <option {{ $category->id == $item->itemCategory->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                              @endforeach
                            </select>
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Description</label>
                            <input type="text" class="form-control" value="{{ $item->description }}" name="description">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Price</label>
                            <input type="number" class="form-control" value="{{ $item->price }}" name="price">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <label class="bmd-label-floating">Image</label>
                          <input type="file" class="form-control" value="{{ $item->image }}" name="image">
                        </div>
                        <br>
                        <a href="{{route('item.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Update Item</button>
                        

                        
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	
@endpush

resources/views/admin/item/index.blade.php
@extends('layouts.app')

@section('title','Item')

@push('css')

	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">


@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <a href="{{route('item.create')}}" class="btn btn-info">Add New Item</a>

              @include('layouts.partial.message')

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">All Item</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="myTable" class="table table-striped table-bordered " style="width:100%;">
                      <thead class=" text-primary">
                        <th style="width: 50px;"> ID </th>
                        <th> Item Name </th>
                        <th> Image </th>
                        <th> Category </th>
                        <th style="width: 320px;"> Description </th>
                        <th style="width: 65px;"> Price </th>
                        <th> Action </th>
                      </thead>
                      <tbody>
                            @foreach($items as $key=>$item)
                            <tr>
              								<td>{{ $key+1 }}</td>
              								<td>{{ $item->name }}</td>
              								<td>
                                <img class="img-responsive img-thumbnail" src="{{ asset('upload/item/'.$item->image) }}" alt="" style="width: 100px; height: 100px;">
                              </td>
                              <td>{{ $item->itemCategory->name }}</td>
                              <td>{{ $item->description }}</td>
                              <td>{{ $item->price }}</td>
                                <td class="text-center">

                                <a href="{{route('item.edit', $item->id)}}"><i class="material-icons mr-3 text-warning mb-3"> edit </i></a>

                                <form id="delete-form-{{$item->id}}" action="{{route('item.destroy', $item->id)}}" style="display: none;" method="POST">
                                  @csrf
                                  @method('DELETE')
                                </form>
                                  <button type="button" style="border:none;background: none;" onclick="if (confirm('Are you sure? You want to delete this Item!')) {
                                        event.preventDefault();
                                        document.getElementById('delete-form-{{$item->id}}').submit();
                                      }else{
                                        event.preventDefault();
                                      }"><i style="cursor: pointer; width: 100%;" class="material-icons text-danger"> delete </i>
                                  </button>

                              </td>
              							</tr>
                            @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')

	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

	<script>
		$(document).ready(function() {
		    $('#myTable').DataTable();
		} );
	</script>

@endpush