routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation', 'Frontend\ReservationController@reserve')->name('reservation');
Route::post('/contact','Frontend\ContactController@contact')->name('contact');



Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'admin'], function(){

	Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');
	Route::resource('slider','SliderController');
	Route::resource('category','CategoryController');
	Route::resource('item','ItemController');
	Route::get('reservation','ReservationController@index')->name('reservation.index');
	Route::post('reservation/{id}','ReservationController@status')->name('reservation.status');
	Route::delete('reservation/{id}','ReservationController@destroy')->name('reservation.destroy');
    Route::get('contact','ContactController@contact')->name('contact.index');
    Route::get('contact/{id}','ContactController@show')->name('contact.show');
    Route::delete('contact/{id}','ContactController@destroy')->name('contact.destroy');
});

resources/views/layouts/partial/footer.blade.php
<footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
              <li>
                <a href="https://creative-tim.com/presentation">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
              <li>
                <a href="https://www.creative-tim.com/license">
                  Licenses
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, made with <i class="material-icons">favorite</i> by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
          </div>
        </div>
      </footer>

resources/views/layouts/partial/message.blade.php
@if ($errors->any())
                      
    @foreach ($errors->all() as $error)

        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none';">
            <i class="material-icons">close</i>
          </button>
          <span>{{ $error }}</span>
        </div>
    @endforeach

@endif

@if(session('successMsg'))
                
		<div class="alert alert-success">
		    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none';">
		      <i class="material-icons">close</i>
		    </button>
		    <span>{{ session('successMsg') }}</span>
		</div>

@endif

resources/views/layouts/partial/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{route('logout')}}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                  <i class="material-icons">exit_to_app</i>
                  <p class="d-lg-none d-md-block">Logout</p>
                </a>
                <form action="{{route('logout')}}" method="POST" style="display: none;" id="logout-form">
                  @csrf
                </form>
              </li>
            </ul>
          </div>
        </div>
      </nav>

resources/views/layouts/partial/sidebar.blade.php
    <div class="sidebar" data-color="purple" data-background-color="white" data-image="{{asset('/')}}backend/assets/img/sidebar-1.jpg">
      <div class="logo">
        <a href="{{route('admin.dashboard')}}" class="simple-text logo-normal">
          Mamma's Kitchen
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item {{Request::is('admin/dashboard*') ? 'active': '' }} ">
            <a class="nav-link" href="{{route('admin.dashboard')}}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item {{Request::is('admin/slider*') ? 'active': '' }}">
            <a class="nav-link " href="{{route('slider.index')}}">
              <i class="material-icons">slideshow</i>
              <p>Sliders</p>
            </a>
          </li>
          <li class="nav-item {{Request::is('admin/category*') ? 'active': '' }}">
            <a class="nav-link " href="{{route('category.index')}}">
              <i class="material-icons">category</i>
              <p>Categories</p>
            </a>
          </li>
          <li class="nav-item {{Request::is('admin/item*') ? 'active': '' }}">
            <a class="nav-link " href="{{route('item.index')}}">
              <i class="material-icons">fastfood</i>
              <p>Items</p>
            </a>
          </li>
          <li class="nav-item {{Request::is('admin/reservation*') ? 'active': '' }}">
            <a class="nav-link " href="{{route('reservation.index')}}">
              <i class="material-icons">library_books</i>
              <p>Reservations</p>
            </a>
          </li>
          <li class="nav-item {{Request::is('admin/contact*') ? 'active': '' }}">
            <a class="nav-link " href="{{route('contact.index')}}">
              <i class="material-icons">message</i>
              <p>Messages</p>
            </a>
          </li>

          <li class="nav-item ">
            <a class="nav-link" href="./map.html">
              <i class="material-icons">location_ons</i>
              <p>Maps</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./notifications.html">
              <i class="material-icons">notifications</i>
              <p>Notifications</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="./rtl.html">
              <i class="material-icons">language</i>
              <p>RTL Support</p>
            </a>
          </li>
          <li class="nav-item active-pro ">
            <a class="nav-link" href="./upgrade.html">
              <i class="material-icons">unarchive</i>
              <p>Upgrade to PRO</p>
            </a>
          </li>
        </ul>
      </div>
    </div>