routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::post('/reservation', 'Frontend\ReservationController@reserve')->name('reservation');
Route::post('/contact','Frontend\ContactController@contact')->name('contact');



Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'admin'], function(){

	Route::get('/dashboard','DashboardController@index')->name('admin.dashboard');
	Route::resource('slider','SliderController');
	Route::resource('category','CategoryController');
	Route::resource('item','ItemController');
	Route::get('reservation','ReservationController@index')->name('reservation.index');
	Route::post('reservation/{id}','ReservationController@status')->name('reservation.status');
	Route::delete('reservation/{id}','ReservationController@destroy')->name('reservation.destroy');
    Route::get('contact','ContactController@contact')->name('contact.index');
    Route::get('contact/{id}','ContactController@show')->name('contact.show');
    Route::delete('contact/{id}','ContactController@destroy')->name('contact.destroy');
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Slider;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders=Slider::all();
        return view('admin.slider.index',compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->all();

        $this->validate($request, [

            'title'     =>'required',
            'sub_title' =>'required',
            'image'     =>'required|mimes:jpeg,jpg,png'
        ]);

        $image= $request->file('image');
        $slug= str_slug($request->title);

        if(isset($image)){

            $currentDate= Carbon::now()->toDateString();
            $imageName= $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            if(!file_exists('upload/slider')){

                mkdir('upload/slider', '0777', 'true');
            }

            $image->move('upload/slider', $imageName);

        }else{

            $imageName= 'default.png';
        }

        $slider= new Slider();
        $slider->title      = $request->title;
        $slider->sub_title  = $request->sub_title;
        $slider->image      = $imageName;
        $slider->save();

        return redirect()->route('slider.index')->with('successMsg','Slider has added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider= Slider::find($id);
        return view('admin.slider.edit',compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [

            'title'     =>'required',
            'sub_title' =>'required',
            'image'     =>'mimes:jpeg,jpg,png'
        ]);

        $image= $request->file('image');
        $slug= str_slug($request->title);
        $slider= Slider::find($id);

        if(isset($image)){

            $currentDate= Carbon::now()->toDateString();
            $imageName= $slug.'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();

            if(!file_exists('upload/slider')){

                mkdir('upload/slider', '0777', 'true');
            }

            $image->move('upload/slider', $imageName);

        }else{

            $imageName= $slider->title;
        }

        $slider->title      = $request->title;
        $slider->sub_title  = $request->sub_title;
        $slider->image      = $imageName;
        $slider->save();

        return redirect()->route('slider.index')->with('successMsg','Slider has updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider=Slider::find($id);

        if (file_exists('upload/slider/'.$slider->image)) 
        { 
            unlink('upload/slider/'.$slider->image);
        }
        $slider->delete();
        return redirect()->back()->with('successMsg','Slider successfully deleted!');
    }
}

resources/views/admin/slider/create.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')
	

	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

              @include('layouts.partial.message')

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Add Slider</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  
                    <form method="POST" action="{{route('slider.store')}}" enctype="multipart/form-data">
                      @csrf
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Title</label>
                            <input type="text" class="form-control" name="title">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Sub Title</label>
                            <input type="text" class="form-control" name="sub_title">
                          </div>
                        </div>
                        
                        <div class="col-md-12">
                          <label class="bmd-label-floating">Image</label>
                          <input type="file" class="form-control" name="image">
                        </div>
                        <br>
                        <a href="{{route('slider.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Add Slider</button>
                        

                        
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	
@endpush

resources/views/admin/slider/edit.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')
	

	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

              @if ($errors->any())
                      
                    @include('layouts.partial.message')

              @endif

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Edit Slider</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  
                    <form method="POST" action="{{route('slider.update', $slider->id)}}" enctype="multipart/form-data">
                      @csrf

                      @method('PUT')

                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Title</label>
                            <input type="text" class="form-control" name="title" value="{{$slider->title}}">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group label-floating">
                            <label class="bmd-label-floating">Sub Title</label>
                            <input type="text" class="form-control" name="sub_title" value="{{$slider->sub_title}}">
                          </div>
                        </div>
                        
                        <div class="col-md-12">
                          <label class="bmd-label-floating">Image</label>
                          <input type="file" class="form-control" name="image">
                        </div>
                        <br>
                        <a href="{{route('slider.index')}}" class="btn btn-warning">Back</a>
                        <button type="submit" class="btn btn-primary">Update Slider</button>
                        

                        
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	
@endpush

resources/views/admin/slider/index.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')
	
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
	
@endpush

@section('content')


	<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <a href="{{route('slider.create')}}" class="btn btn-info">Add New Slider</a>

              @include('layouts.partial.message')

              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">All Slider</h4>
                  <p class="card-category"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae, perferendis.</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="myTable" class="table table-striped table-bordered " style="width:100%;">
                      <thead class=" text-primary">
                        <th class="mr-3">
                          ID  
                        </th>
                        <th>
                          Title
                        </th>
                        <th>
                          Sub-title
                        </th>
                        <th>
                          Image
                        </th>
                        <th>
                          Action
                        </th>
                      </thead>
                      <tbody>
                         @foreach($sliders as $key=>$slider)


							<tr>
								<td>{{$key+1}}</td>
								<td>{{$slider->title}}</td>
								<td>{{$slider->sub_title}}</td>
								<td>{{$slider->image}}</td>
								<td class="text-center">

                  <a href="{{route('slider.edit', $slider->id)}}"><i class="material-icons mr-3 text-warning mb-3">edit</i></a>

                  <form id="delete-form-{{$slider->id}}" action="{{route('slider.destroy', $slider->id)}}" style="display: none;" method="POST">
                    @csrf
                    @method('DELETE')
                  </form>
                  <button type="button" style="border:none;background: none;" onclick="if (confirm('Are you sure? You want to delete this slide!')) {
                        event.preventDefault();
                        document.getElementById('delete-form-{{$slider->id}}').submit();
                      }else{
                        event.preventDefault();
                      }"><i style="cursor: pointer; width: 100%;" class="material-icons text-danger">delete</i>
                  </button>
                    
                </td>
							</tr>


                         @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>




@endsection

@push('scripts')
	
	<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

	<script>
		$(document).ready(function() {
		    $('#myTable').DataTable();
		} );
	</script>
	
@endpush